name: Pipline CI/CD portfolio
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
