name: Pipeline CI/CD Portfolio

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Uncomment and modify if test jobs are needed
  # test:
  #   runs-on: ubuntu-latest
  #   needs: check_syntaxe
  #   services:
  #     postgres:
  #       image: postgres:15.8
  #       env:
  #         POSTGRES_USER: portfolio
  #         POSTGRES_PASSWORD: portfolio
  #         POSTGRES_DB: portfolio_db
  #       ports:
  #         - 5459:5432
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.12'
  #     - name: Install dependencies
  #       run: make install_dev
  #     # - name: Run tests
  #     #   run: make test

  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: [check_syntaxe]

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build the Docker image
        run: docker build . -t laminebalde/movie-review:ubuntu-latest

      - name: Push the Docker image
        run: docker push laminebalde/movie-review:ubuntu-latest
